SKILLS = [
    "python",
    "java",
    "sql",
    "machine learning",
    "deep learning",
    "tensorflow",
    "keras",
    "scikit-learn",
    "opencv",
    "numpy",
    "pandas",
    "matplotlib",
    "seaborn",
    "power bi",
    "tableau",
    "excel",
    "git",
    "docker",
    "kubernetes",
    "aws",
    "azure",
    "gcp",
    "flask",
    "django",
    "streamlit",
    "nlp",
    "computer vision",
    "generative ai",
    "langchain"
]